import { generateId } from './utils';

export function createDefaultBlocks() {
  return [
    {
      id: generateId('block_capsule'),
      type: 'banner',
      title: 'Capsule Waving Banner',
      hideHeader: true,
      alignment: 'center',
      badgeStyle: 'flat',
      isCollapsed: false,
      bannerType: 'capsule',
      imageUrl: '',
      capsuleText: 'Welcome to my Profile',
      capsuleType: 'waving',
      capsuleColor: 'gradient',
      capsuleCustomColors: '6,11,20,29',
      capsuleHeight: 200,
      capsuleFontSize: 48,
      capsuleAnimation: 'twinkling',
      showProfileViews: true,
      githubUsername: 'your-username',
      viewsLabel: 'Profile views',
      viewsColor: '0e75b6',
      viewsStyle: 'flat',
      titleText: '',
      useTocStyle: false,
    },
    {
      id: generateId('block_hero'),
      type: 'hero',
      title: 'Hero Section',
      hideHeader: true,
      alignment: 'center',
      badgeStyle: 'for-the-badge',
      isCollapsed: false,
      name: 'Your Name',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      avatarShape: 'circle',
      avatarSize: 120,
      subtitleType: 'typing',
      subtitleText: 'Full Stack Engineer & Open Source Contributor',
      typingLines: [
        'Full Stack Engineer',
        'TypeScript & React Enthusiast',
        'Building scalable web applications',
      ],
      typingColor: '61afef',
      typingFont: 'Fira Code',
      bioText: "I'm a software engineer focused on building clean, accessible, and high-performance developer tools and web applications.",
      socialBadges: [
        { id: generateId('soc'), platform: 'GitHub', label: 'GitHub', url: 'https://github.com', color: '181717', logo: 'github' },
        { id: generateId('soc'), platform: 'LinkedIn', label: 'LinkedIn', url: 'https://linkedin.com', color: '0A66C2', logo: 'linkedin' },
        { id: generateId('soc'), platform: 'Twitter', label: 'X', url: 'https://x.com', color: '000000', logo: 'x' },
      ],
    },
    {
      id: generateId('block_rapidfire'),
      type: 'rapid-fire',
      title: 'About Me',
      hideHeader: false,
      alignment: 'left',
      badgeStyle: 'flat',
      isCollapsed: false,
      tagline: 'Passionate developer creating robust and scalable web applications with a focus on user experience.',
      items: [
        { id: generateId('rf'), icon: '-', label: "I'm currently working on", text: 'Open source developer tools and web apps' },
        { id: generateId('rf'), icon: '-', label: "I'm currently learning", text: 'Distributed systems and cloud architecture' },
        { id: generateId('rf'), icon: '-', label: 'Ask me about', text: 'React, TypeScript, UI/UX, Backend' },
        { id: generateId('rf'), icon: '-', label: 'Fun fact', text: 'Always exploring new technology and developer productivity tools' },
      ],
    },
    {
      id: generateId('block_skills'),
      type: 'skills',
      title: 'Skills & Tech Stack',
      hideHeader: false,
      alignment: 'center',
      badgeStyle: 'flat',
      isCollapsed: false,
      useFlexContainer: true,
      badgeHeight: 28,
      categories: [
        {
          id: generateId('cat'),
          name: '',
          badges: [
            { id: generateId('badge'), name: 'TypeScript', color: '3178C6', logo: 'typescript' },
            { id: generateId('badge'), name: 'JavaScript', color: 'F7DF1E', logo: 'javascript' },
            { id: generateId('badge'), name: 'React', color: '20232A', logo: 'react' },
            { id: generateId('badge'), name: 'Next.js', color: '000000', logo: 'nextdotjs' },
            { id: generateId('badge'), name: 'Tailwind CSS', color: '38B2AC', logo: 'tailwind-css' },
            { id: generateId('badge'), name: 'Node.js', color: '339933', logo: 'nodedotjs' },
            { id: generateId('badge'), name: 'PostgreSQL', color: '316192', logo: 'postgresql' },
            { id: generateId('badge'), name: 'Python', color: '306998', logo: 'python' },
            { id: generateId('badge'), name: 'Docker', color: '2496ED', logo: 'docker' },
            { id: generateId('badge'), name: 'Figma', color: 'F24E1E', logo: 'figma' },
          ],
        },
      ],
    },
    {
      id: generateId('block_stats'),
      type: 'github-stats',
      title: 'GitHub Stats',
      hideHeader: false,
      alignment: 'center',
      badgeStyle: 'flat',
      isCollapsed: false,
      username: 'your-username',
      theme: 'default',
      cardWidth: '48%',
      showStatsCard: true,
      showTopLangs: true,
      showStreakCard: true,
    },
  ];
}

export function getPresetTemplates() {
  return {
    modern: {
      label: 'Modern Full Stack Engineer',
      desc: 'Capsule waving gradient header, avatar with typing SVG, rapid fire bullets, flex tech stack, and stats cards.',
      blocks: createDefaultBlocks(),
    },
    alex: {
      label: 'Alex Rivera (Typing SVG Hero)',
      desc: 'Hero with animated Typing SVG, avatar, categorized tech stack, experience timeline, and project showcase.',
      blocks: [
        {
          id: generateId('block_hero'),
          type: 'hero',
          title: 'Hero Section',
          hideHeader: true,
          alignment: 'center',
          badgeStyle: 'for-the-badge',
          name: 'Alex Rivera',
          avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
          avatarShape: 'circle',
          avatarSize: 130,
          subtitleType: 'typing',
          subtitleText: 'Full Stack Engineer & Open Source Contributor',
          typingLines: [
            'Full Stack Engineer',
            'TypeScript & Node Enthusiast',
            'Building high-scale cloud platforms',
            'Open Source Creator',
          ],
          typingColor: '61afef',
          typingFont: 'Fira Code',
          bioText: "I'm a software engineer focused on distributed systems, developer tooling, and modern web architectures.",
          socialBadges: [
            { id: generateId('soc'), platform: 'GitHub', label: 'GitHub', url: 'https://github.com', color: '181717', logo: 'github' },
            { id: generateId('soc'), platform: 'LinkedIn', label: 'LinkedIn', url: 'https://linkedin.com', color: '0A66C2', logo: 'linkedin' },
            { id: generateId('soc'), platform: 'Twitter', label: 'Twitter', url: 'https://x.com', color: '000000', logo: 'x' },
            { id: generateId('soc'), platform: 'Website', label: 'Portfolio', url: 'https://alexrivera.dev', color: 'FF5722', logo: 'googlechrome' },
          ],
        },
        {
          id: generateId('block_skills'),
          type: 'skills',
          title: 'Tech Stack & Skills',
          hideHeader: false,
          alignment: 'left',
          badgeStyle: 'flat',
          categories: [
            {
              id: generateId('cat'),
              name: 'Core Languages',
              badges: [
                { id: generateId('badge'), name: 'TypeScript', color: '3178C6', logo: 'typescript' },
                { id: generateId('badge'), name: 'JavaScript', color: 'F7DF1E', logo: 'javascript' },
                { id: generateId('badge'), name: 'Python', color: '306998', logo: 'python' },
                { id: generateId('badge'), name: 'Go', color: '00ADD8', logo: 'go' },
              ],
            },
            {
              id: generateId('cat'),
              name: 'Frameworks & Libraries',
              badges: [
                { id: generateId('badge'), name: 'React', color: '20232A', logo: 'react' },
                { id: generateId('badge'), name: 'Next.js', color: '000000', logo: 'nextdotjs' },
                { id: generateId('badge'), name: 'Tailwind CSS', color: '38B2AC', logo: 'tailwindcss' },
              ],
            },
          ],
        },
        {
          id: generateId('block_proj'),
          type: 'projects',
          title: 'Featured Projects',
          hideHeader: false,
          alignment: 'left',
          badgeStyle: 'flat',
          layout: '2-col',
          items: [
            {
              id: generateId('proj'),
              title: 'Aura CLI — Cloud Deployment Engine',
              description: 'Lightweight CLI tool for zero-config preview deployments to cloud providers.',
              repoUrl: 'https://github.com',
              demoUrl: 'https://example.com',
              imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
              techBadges: ['JavaScript', 'Docker', 'AWS'],
            },
          ],
        },
      ],
    },
    devops: {
      label: 'DevOps & Cloud Architect',
      desc: 'Focus on Kubernetes, AWS, Terraform, CI/CD pipelines, and infrastructure architecture.',
      blocks: [
        {
          id: generateId('block_hero'),
          type: 'hero',
          title: 'Hero Section',
          hideHeader: true,
          alignment: 'center',
          badgeStyle: 'for-the-badge',
          name: 'Jordan Taylor',
          avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
          avatarShape: 'rounded',
          avatarSize: 130,
          subtitleType: 'typing',
          subtitleText: 'Cloud Architect & Platform Engineer',
          typingLines: [
            'DevOps & Platform Engineer',
            'Kubernetes & Infrastructure-as-Code',
            'Automating high-availability systems',
          ],
          typingColor: '326CE5',
          typingFont: 'Fira Code',
          bioText: 'Focused on zero-downtime deployments, distributed reliability, and scalable infrastructure.',
          socialBadges: [
            { id: generateId('soc'), platform: 'GitHub', label: 'GitHub', url: 'https://github.com', color: '181717', logo: 'github' },
            { id: generateId('soc'), platform: 'LinkedIn', label: 'LinkedIn', url: 'https://linkedin.com', color: '0A66C2', logo: 'linkedin' },
          ],
        },
        {
          id: generateId('block_skills'),
          type: 'skills',
          title: 'Infrastructure & Tooling',
          hideHeader: false,
          alignment: 'left',
          badgeStyle: 'for-the-badge',
          categories: [
            {
              id: generateId('cat'),
              name: 'Cloud & Containers',
              badges: [
                { id: generateId('badge'), name: 'AWS', color: '232F3E', logo: 'amazonwebservices' },
                { id: generateId('badge'), name: 'Docker', color: '2496ED', logo: 'docker' },
                { id: generateId('badge'), name: 'Kubernetes', color: '326CE5', logo: 'kubernetes' },
                { id: generateId('badge'), name: 'Terraform', color: '7B42BC', logo: 'terraform' },
              ],
            },
          ],
        },
      ],
    },
    minimal: {
      label: 'Minimalist Clean',
      desc: 'Clean profile with avatar, brief bio, top tools, and links.',
      blocks: [
        {
          id: generateId('block_hero'),
          type: 'hero',
          title: 'Hero Section',
          hideHeader: true,
          alignment: 'center',
          badgeStyle: 'flat',
          name: 'Morgan Lee',
          avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
          avatarShape: 'circle',
          avatarSize: 110,
          subtitleType: 'static',
          subtitleText: 'Software Engineer & Open Source Contributor',
          typingLines: [],
          typingColor: '000000',
          typingFont: 'Fira Code',
          bioText: 'Writing concise, elegant code and building developer tooling.',
          socialBadges: [
            { id: generateId('soc'), platform: 'GitHub', label: 'GitHub', url: 'https://github.com', color: '181717', logo: 'github' },
            { id: generateId('soc'), platform: 'Twitter', label: 'X', url: 'https://x.com', color: '000000', logo: 'x' },
          ],
        },
        {
          id: generateId('block_skills'),
          type: 'skills',
          title: 'Languages & Tools',
          hideHeader: false,
          alignment: 'center',
          badgeStyle: 'flat',
          categories: [
            {
              id: generateId('cat'),
              name: '',
              badges: [
                { id: generateId('badge'), name: 'JavaScript', color: 'F7DF1E', logo: 'javascript' },
                { id: generateId('badge'), name: 'React', color: '20232A', logo: 'react' },
                { id: generateId('badge'), name: 'Node.js', color: '339933', logo: 'nodedotjs' },
                { id: generateId('badge'), name: 'PostgreSQL', color: '316192', logo: 'postgresql' },
              ],
            },
          ],
        },
      ],
    },
  };
}
